// Code generated - EDITING IS FUTILE. DO NOT EDIT.
//
// Generated by:
//     kinds/gen.go
// Using jennies:
//     TSTypesJenny
//     LatestMajorsOrXJenny
//
// Run 'make gen-cue' from repository root to regenerate.

export interface QueryHistoryPreference {
  /**
   * one of: '' | 'query' | 'starred';
   */
  homeTab?: string;
}

export interface CookiePreferences {
  analytics?: Record<string, unknown>;
  functional?: Record<string, unknown>;
  performance?: Record<string, unknown>;
}

export interface NavbarPreference {
  bookmarkUrls: Array<string>;
}

export const defaultNavbarPreference: Partial<NavbarPreference> = {
  bookmarkUrls: [],
};

/**
 * Theme customization options for dark mode
 */
export interface ThemeCustomization {
  /**
   * Contrast level: 'default' | 'high' | 'low'
   */
  contrastLevel?: string;
  /**
   * Custom accent color (hex color code)
   */
  accentColor?: string;
  /**
   * Custom primary color (hex color code)
   */
  primaryColor?: string;
  /**
   * Custom background color (hex color code)
   */
  backgroundColor?: string;
  /**
   * Custom text color (hex color code)
   */
  textColor?: string;
}

export const defaultThemeCustomization: Partial<ThemeCustomization> = {
  contrastLevel: 'default',
};

/**
* Spec defines user, team or org Grafana preferences
* swagger:model Preferences
*/
export interface Preferences {
  /**
   * Cookie preferences
   */
  cookiePreferences?: CookiePreferences;
  /**
   * UID for the home dashboard
   */
  homeDashboardUID?: string;
  /**
   * Selected language (beta)
   */
  language?: string;
  /**
   * Navigation preferences
   */
  navbar?: NavbarPreference;
  /**
   * Explore query history preferences
   */
  queryHistory?: QueryHistoryPreference;
  /**
   * Selected locale (beta)
   */
  regionalFormat?: string;
  /**
   * light, dark, empty is default
   */
  theme?: string;
  /**
   * Theme customization options
   */
  themeCustomization?: ThemeCustomization;
  /**
   * The timezone selection
   * TODO: this should use the timezone defined in common
   */
  timezone?: string;
  /**
   * day of the week (sunday, monday, etc)
   */
  weekStart?: string;
}
